# Generated by Django 2.2 on 2022-12-25 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attached_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(null=True, upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=100)),
                ('available_language', models.CharField(max_length=50)),
                ('course_description', models.TextField()),
                ('over_view', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.CharField(max_length=2)),
                ('chapter_name', models.CharField(max_length=150)),
                ('chapter_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insturctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Insturctor_name', models.CharField(max_length=100)),
                ('Insturctor_image', models.ImageField(upload_to='uploads/')),
                ('description', models.TextField()),
                ('NumOfStudent', models.IntegerField()),
                ('Insturctor_rate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=300)),
                ('review_date', models.DateTimeField(auto_now=True)),
                ('review_rate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
        ),
        migrations.CreateModel(
            name='session_summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('noteImag', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_course', models.FileField(null=True, upload_to='upload videos/', verbose_name='')),
                ('chapters', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='COURSES_PROVIEW_api.chapters')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_course', models.ImageField(upload_to='uploads/')),
                ('Course_name', models.CharField(max_length=150)),
                ('details', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(max_length=50)),
                ('book_live_session', models.FileField(null=True, upload_to='book')),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='COURSES_PROVIEW_api.Category')),
                ('instructor', models.ManyToManyField(related_name='courses', to='COURSES_PROVIEW_api.Insturctor')),
            ],
        ),
        migrations.AddField(
            model_name='chapters',
            name='Course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='COURSES_PROVIEW_api.Course'),
        ),
        migrations.AddField(
            model_name='chapters',
            name='attached_files',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='COURSES_PROVIEW_api.attached_files'),
        ),
        migrations.AddField(
            model_name='chapters',
            name='session_summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='COURSES_PROVIEW_api.session_summary'),
        ),
        migrations.AddField(
            model_name='category',
            name='Insturctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='COURSES_PROVIEW_api.Insturctor'),
        ),
    ]
